export const mockTickets = [
  // ── WhatsApp ──────────────────────────────────────────────
  {
    id: "TIC-8291",
    customerName: "Sarah Jenkins",
    initials: "SJ",
    subject: "Problem with my order #4829",
    time: "12:45 PM",
    status: "new",
    hasDraft: true,
    avatarVariant: "blue",
    email: "sarah.j@example.com",
    category: "Order Issue",
    content: "Hi support, I haven't received my order yet. It's been 5 days.",
    sentiment: "Frustrated",
    channel: "whatsapp",
  },
  {
    id: "TIC-8295",
    customerName: "Fatima Noor",
    initials: "FN",
    subject: "Can't track my shipment",
    time: "10:30 AM",
    status: "pending",
    hasDraft: true,
    avatarVariant: "teal",
    email: "fatima.n@gmail.com",
    category: "Shipping",
    content: "The tracking link you sent isn't working. I need to know where my package is.",
    sentiment: "Frustrated",
    channel: "whatsapp",
  },
  {
    id: "TIC-8299",
    customerName: "Omar Hassan",
    initials: "OH",
    subject: "Refund not received after 7 days",
    time: "08:10 AM",
    status: "escalated",
    hasDraft: false,
    avatarVariant: "purple",
    email: "omar.h@outlook.com",
    category: "Refund",
    content: "I returned the item over a week ago and still haven't gotten my money back. This is unacceptable.",
    sentiment: "Angry",
    channel: "whatsapp",
  },
  // ── Facebook Messenger ────────────────────────────────────
  {
    id: "TIC-8292",
    customerName: "Michael Chen",
    initials: "MC",
    subject: "Question about premium subscription",
    time: "11:20 AM",
    status: "pending",
    hasDraft: false,
    avatarVariant: "teal",
    email: "m.chen@techcorp.io",
    category: "Billing",
    content: "I want to upgrade to the annual plan, can I get a pro-rated discount?",
    sentiment: "Neutral",
    channel: "facebook",
  },
  {
    id: "TIC-8296",
    customerName: "Amelia Brooks",
    initials: "AB",
    subject: "App keeps crashing on iPhone",
    time: "09:55 AM",
    status: "new",
    hasDraft: true,
    avatarVariant: "green",
    email: "amelia.b@icloud.com",
    category: "Tech Support",
    content: "Every time I open the app on my iPhone 14 it crashes within seconds. Please fix this!",
    sentiment: "Frustrated",
    channel: "facebook",
  },
  {
    id: "TIC-8300",
    customerName: "Tariq Mehmood",
    initials: "TM",
    subject: "Wrong item delivered",
    time: "07:40 AM",
    status: "escalated",
    hasDraft: false,
    avatarVariant: "blue",
    email: "tariq.m@gmail.com",
    category: "Order Issue",
    content: "I ordered a blue shirt size L and received a red one in XS. This is ridiculous.",
    sentiment: "Angry",
    channel: "facebook",
  },
  // ── Website Live Chat ─────────────────────────────────────
  {
    id: "TIC-8293",
    customerName: "Averie Miller",
    initials: "AM",
    subject: "URGENT: Billing error on my statement",
    time: "09:15 AM",
    status: "escalated",
    hasDraft: true,
    avatarVariant: "purple",
    email: "averie@miller.com",
    category: "Refund",
    content: "I was double charged! Please fix this immediately or I'll file a dispute.",
    sentiment: "Angry",
    channel: "website",
  },
  {
    id: "TIC-8294",
    customerName: "David Wilson",
    initials: "DW",
    subject: "Feature request for mobile app",
    time: "08:30 AM",
    status: "pending",
    hasDraft: true,
    avatarVariant: "green",
    email: "dwilson@gmail.com",
    category: "Feedback",
    content: "The app is great, but multi-user support would be a game changer.",
    sentiment: "Positive",
    channel: "website",
  },
  {
    id: "TIC-8297",
    customerName: "Priya Sharma",
    initials: "PS",
    subject: "Cannot login to my account",
    time: "11:05 AM",
    status: "new",
    hasDraft: true,
    avatarVariant: "teal",
    email: "priya.s@gmail.com",
    category: "Tech Support",
    content: "I reset my password but the new one isn't working either. Please help!",
    sentiment: "Frustrated",
    channel: "website",
  },
  {
    id: "TIC-8298",
    customerName: "James Okafor",
    initials: "JO",
    subject: "Invoice missing from portal",
    time: "10:00 AM",
    status: "pending",
    hasDraft: false,
    avatarVariant: "blue",
    email: "j.okafor@business.com",
    category: "Billing",
    content: "My invoice for last month is not showing in the billing portal. I need it for accounting.",
    sentiment: "Neutral",
    channel: "website",
  },
];

export const mockStats = {
  openTickets: 10,
  aiDraftsReady: 6,
  avgResponseTime: "3m 48s",
  csatScore: 4.7,
  volumeTrend: [
    { label: "Mon", value: 45 },
    { label: "Tue", value: 52 },
    { label: "Wed", value: 38 },
    { label: "Thu", value: 65 },
    { label: "Fri", value: 48 },
    { label: "Sat", value: 24, highlight: true },
    { label: "Sun", value: 18 },
  ],
  categories: [
    { name: "Order Issues", value: 42, color: "bg-brand" },
    { name: "Billing", value: 28, color: "bg-teal" },
    { name: "Tech Support", value: 22, color: "bg-purple" },
    { name: "General Info", value: 8, color: "bg-warn" },
  ],
  // Per-channel reply rate data (avg minutes to first reply)
  channelReplyRates: [
    {
      channel: "WhatsApp",
      color: "#25D366",
      data: [
        { day: "Mon", mins: 2.1 },
        { day: "Tue", mins: 1.8 },
        { day: "Wed", mins: 3.2 },
        { day: "Thu", mins: 1.5 },
        { day: "Fri", mins: 2.4 },
        { day: "Sat", mins: 4.1 },
        { day: "Sun", mins: 5.2 },
      ],
      avgMins: 2.3,
      totalTickets: 3,
      escalated: 1,
    },
    {
      channel: "Facebook",
      color: "#1877F2",
      data: [
        { day: "Mon", mins: 4.5 },
        { day: "Tue", mins: 5.2 },
        { day: "Wed", mins: 3.8 },
        { day: "Thu", mins: 6.1 },
        { day: "Fri", mins: 4.9 },
        { day: "Sat", mins: 7.3 },
        { day: "Sun", mins: 8.0 },
      ],
      avgMins: 5.7,
      totalTickets: 3,
      escalated: 1,
    },
    {
      channel: "Website",
      color: "#14B8A6",
      data: [
        { day: "Mon", mins: 1.2 },
        { day: "Tue", mins: 0.9 },
        { day: "Wed", mins: 1.5 },
        { day: "Thu", mins: 1.1 },
        { day: "Fri", mins: 2.0 },
        { day: "Sat", mins: 1.8 },
        { day: "Sun", mins: 3.1 },
      ],
      avgMins: 1.7,
      totalTickets: 4,
      escalated: 1,
    },
  ],
};

export const mockChannels = [
  { id: "gmail", name: "Gmail", description: "Official support inbox connection", connected: false },
  { id: "whatsapp", name: "WhatsApp Business", description: "Customer chat integration", connected: true },
  { id: "facebook", name: "Facebook Messenger", description: "Messenger inbox integration", connected: true },
  { id: "livechat", name: "Web Live Chat", description: "In-app support widget", connected: true },
  { id: "instagram", name: "Instagram DMs", description: "Direct message management", connected: false },
];
